language: python

dist: xenial

python:
 - "3.7"

services:
 - docker

before_install: export PYTHONPATH=$PYTHONPATH:$(pwd)

before_script: pip install -r requirements.txt

script:
  - python project/tests/first_test.py
